version: '3'

services:
  db:
    image: postgres
    container_name: ${DATABASE_NAME}
    restart: always
    ports:
      - "$DATABASE_PORT:5432"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_NAME}
